run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2
  revive:
    rules:
      - name: string-format
        severity: error
        disabled: false
        arguments:
          - - 'fmt.Errorf[0]'
            - "/^[^A-Z].*$/"
            - error messages must not start with capital letter
          - - 'log.Printf[0]'
            - "/^[^a-z].*$/"
            - log messages must not start with lowercase letter
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - GitLab

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - typecheck
    - exportloopref
    - prealloc
    # - wls # excluded from linters list because produces too many noise
    - staticcheck
    - unused
    - contextcheck
    - durationcheck
    - errname
    - exhaustive
    - gocritic
    - gofmt
    - nilerr
    - nilnil
    - usestdlibvars
    - misspell
