run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - exportloopref
    - prealloc
    - wsl